# Raspberry Pi 4 Configuration (BCM2711)

# Target
CONFIG_TARGET_bcm27xx=y
CONFIG_TARGET_bcm27xx_bcm2711=y

# Build toolchain
CONFIG_MAKE_TOOLCHAIN=y

# Compiler
CONFIG_GCC_VERSION_11=y
CONFIG_BINUTILS_VERSION_2_37=y

# C Library
CONFIG_LIBC_USE_GLIBC=y

# Kernel
CONFIG_TARGET_KERNEL_PARTSIZE=64
CONFIG_TARGET_ROOTFS_PARTSIZE=1024
CONFIG_KERNEL_BUILD_USER="isaac"
CONFIG_KERNEL_BUILD_DOMAIN="github.com"