# Rockchip ARMv8 Configuration
# For NanoPi R2S/R4S, Orange Pi R1 Plus, etc.

# Target
CONFIG_TARGET_rockchip=y
CONFIG_TARGET_rockchip_armv8=y

# Build toolchain
CONFIG_MAKE_TOOLCHAIN=y

# C Library
CONFIG_LIBC_USE_MUSL=y

# Kernel
CONFIG_TARGET_KERNEL_PARTSIZE=64
CONFIG_TARGET_ROOTFS_PARTSIZE=1024
CONFIG_KERNEL_BUILD_USER="isaac"
CONFIG_KERNEL_BUILD_DOMAIN="github.com"