# x86_64 Target Configuration
# For PC, firewall appliance, mini PC (Intel/AMD)

# Target
CONFIG_TARGET_x86=y
CONFIG_TARGET_x86_64=y
CONFIG_TARGET_x86_64_Generic=y

# Build toolchain (not full firmware)
CONFIG_MAKE_TOOLCHAIN=y

# C Library
CONFIG_LIBC_USE_GLIBC=y

# Kernel
CONFIG_TARGET_KERNEL_PARTSIZE=256
CONFIG_TARGET_ROOTFS_PARTSIZE=2048
CONFIG_KERNEL_BUILD_USER="isaac"
CONFIG_KERNEL_BUILD_DOMAIN="github.com"

# Output
CONFIG_TARGET_ROOTFS_TARGZ=y